### ISSUE TITLE
Not working when Deploying to Azure

### ISSUE THREAD

**Issue by scarbon** [BorisWilhelms/azure-function-dependency-injection#11]
It works locally running on Runtime version: 2.0.12115.0 (same as Azure) and Microsoft.NET.Sdk.Functions Version="1.0.22" but not In Azure

Error indexing method 'XXXXXX.Run' Cannot bind parameter 'worker' to type IXXXXXX.. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

**Comment by BorisWilhelms** [comment]
There is an issue with the `ExtensionsMetadataGenerator`, which generates the needed `extensions.json`. 
Someone posted a workaround for this issue in the corrospondig issue: https://github.com/Azure/azure-functions-host/issues/3386#issuecomment-419565714

Just download the `Directory.build.targets` file and place it into your project directory, this should copy the correct `extensions.json` file on publish. Hopefully MS will fix this in their SDK.

I will update the readme file.

**Comment by scarbon** [comment]
Thank you Boris, thanks for taking your time to help me on this, it worked perfectly :)

**Comment by nmagesh84** [comment]
Hi Boris, Scarbon,

 I did tried the approach of adding directory.build.targets file in the project directory and when I build or publish the application, the extensions.json was created in bin folder with the startup class name and its type.

However when i deployed the code in app, I get the same binding error mentioned in he post. Is there any other settings i need to do in the azure portal ? 

The DI works perfectly in my local environment. I use function V2.0 with dotnet core 2.1. Please advise.

thanks,
Magesh

**Comment by BorisWilhelms** [comment]
@nmagesh84 could you please check that the runtime is set to version 2 in your function application:

![grafik](https://user-images.githubusercontent.com/1989935/46493612-1e1cc000-c811-11e8-8f2a-22d92960b96d.png)

You can find the setting in the `Function App Settings`

**Comment by nmagesh84** [comment]
Thanks Boris for your prompt reply, i have ~2 runtime version only. I will double check my code again and will update you.

**Comment by calebsmithdev** [comment]
Thanks to @scarbon I was able to get one function up and running well! But if I deploy another Azure Function within the same Function App, I get an error like the original. It's really weird. If I were to republish the error-proned Azure Function, the error is no longer present, but now the other one is having issues.

Anyone have recommendations on how to fix this, or a workaround for it?

Update: After a lot of trial and error, I discovered it was related to the extensions.json file and the way I setup my dependencies in the different projects. Since it looks like for "Startup" and looks for the specific file in the last published function, that doesn't jive well with multiple functions. The `bin` is shared with the entire Function App, versus each AF having their own folder for uniqueness. I added my AF business logic to its own project, made sure the startup for each function had the same dependencies and then published. All works great now!
